package net.gudenau.jusb;

import java.io.IOException;

/**
 * An exception generated by failures in the USB subsystem.
 */
public class UsbException extends IOException {
    /**
     * Constructs a UsbException with the specified detail message.
     *
     * @param message The detail message
     */
    public UsbException(String message) {
        super(message);
    }
    
    /**
     * Constructs a UsbException with the specified detail message and cause.
     *
     * @param message The detail message
     * @param cause The cause of this exception
     */
    public UsbException(String message, Throwable cause) {
        super(message, cause);
    }
    
    /**
     * Constructs a UsbException with the specified cause.
     *
     * @param cause The cause of this exception
     */
    public UsbException(Throwable cause) {
        super(cause);
    }
}
